### ISSUE TITLE
When trying to add a channel

### ISSUE THREAD

**Issue by tony-rsrv** [MrBrax/LiveStreamDVR#278]
`
TypeError: Converting circular structure to JSON
--> starting at object with constructor 'Timeout'
| property '_idlePrev' -> object with constructor 'TimersList'
--- property '_idleNext' closes the circle
at JSON.stringify (<anonymous>)
at stringify (/usr/local/share/twitchautomator/server/node_modules/express/lib/response.js:1150:12)
at ServerResponse.json (/usr/local/share/twitchautomator/server/node_modules/express/lib/response.js:271:14)
at ServerResponse.send2 (/usr/local/share/twitchautomator/server/node_modules/express/lib/response.js:162:21)
at AddChannel (/usr/local/share/twitchautomator/server/src/Controllers/Channels.ts:273:9)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
`

**Comment by MrBrax** [comment]
this is odd, doesn't seem to be happening on my end.. any more logging around it?

**Comment by tony-rsrv** [comment]
`
2022-08-31 10:45:32.854 | helper <INFO> Querying streams for streamer id xxxxx
2022-08-31 10:45:32.856 | route.channels.add <SUCCESS> Created channel: xxxxxxx
TypeError: Converting circular structure to JSON
--> starting at object with constructor 'Timeout'
| property '_idlePrev' -> object with constructor 'TimersList'
--- property '_idleNext' closes the circle
at JSON.stringify (<anonymous>)
at stringify (/usr/local/share/twitchautomator/server/node_modules/express/lib/response.js:1150:12)
at ServerResponse.json (/usr/local/share/twitchautomator/server/node_modules/express/lib/response.js:271:14)
at ServerResponse.send2 (/usr/local/share/twitchautomator/server/node_modules/express/lib/response.js:162:21)
at AddChannel (/usr/local/share/twitchautomator/server/src/Controllers/Channels.ts:273:9)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (node:internal/process/task_queues:96:5)

Node.js v17.9.1
error Command failed with exit code 1.
`

Happens with any channel, and this is the entire error. Note that this is the unRAID app.

**Comment by MrBrax** [comment]
is this with an initial setup and no channels added?

**Comment by tony-rsrv** [comment]
Happens with zero existing channels or ten existing channels. Once it crashes, restarting the Docker container, everything seems to be fine and the channel is added (although I haven't had a channel go live yet to verify that watching the channel is working). There are no errors in the UI once a restart is completed.

**Comment by tony-rsrv** [comment]
Just tested with the develop branch, no errors now! Thank you for the quick fix!
