### ISSUE TITLE
Check Muted Crashes Program

### ISSUE THREAD

**Issue by tony-rsrv** [MrBrax/LiveStreamDVR#284]
`
TypeError: Converting circular structure to JSON
--> starting at object with constructor 'FSWatcher'
| property '_nodeFsHandler' -> object with constructor 'NodeFsHandler'
--- property 'fsw' closes the circle
at JSON.stringify (<anonymous>)
at stringify (/usr/local/share/twitchautomator/server/node_modules/express/lib/response.js:1150:12)
at ServerResponse.json (/usr/local/share/twitchautomator/server/node_modules/express/lib/response.js:271:14)
at ServerResponse.send2 (/usr/local/share/twitchautomator/server/node_modules/express/lib/response.js:162:21)
at CheckMute (/usr/local/share/twitchautomator/server/src/Controllers/Vod.ts:260:9)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (node:internal/process/task_queues:96:5)

Node.js v17.9.1
`

**Comment by MrBrax** [comment]
odd how these starting popping up just now

**Comment by tony-rsrv** [comment]
I also had an issue, when it crashed, a VOD was downloading and now I'm stuck here: https://i.tony.pm/Mdt38VO.png
What should I do to delete that and re-download the VOD?

**Comment by MrBrax** [comment]
probably best off deleting the json file for it and restarting the server
