### ISSUE TITLE
Unable to start

### ISSUE THREAD

**Issue by CappiSteijns** [MrBrax/LiveStreamDVR#300]
Hi, 

Using this docker for months but suddenly I cant start the container anymore. I get the following error:

```
/usr/local/share/twitchautomator/server/src/index.ts:57
            throw new Error("Server has been started with an older version than the data folder. Use the argument --ignore-version to continue.");
            ^


Error: Server has been started with an older version than the data folder. Use the argument --ignore-version to continue.
    at Object.<anonymous> (/usr/local/share/twitchautomator/server/src/index.ts:57:19)
    at Module._compile (node:internal/modules/cjs/loader:1119:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
    at Module.load (node:internal/modules/cjs/loader:997:32)
    at Module._load (node:internal/modules/cjs/loader:838:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:18:47

Node.js v18.9.0
error Command failed with exit code 1.
/usr/local/share/twitchautomator/server/src/index.ts:57
            throw new Error("Server has been started with an older version than the data folder. Use the argument --ignore-version to continue.");
            ^


Error: Server has been started with an older version than the data folder. Use the argument --ignore-version to continue.
    at Object.<anonymous> (/usr/local/share/twitchautomator/server/src/index.ts:57:19)
    at Module._compile (node:internal/modules/cjs/loader:1119:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
    at Module.load (node:internal/modules/cjs/loader:997:32)
    at Module._load (node:internal/modules/cjs/loader:838:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:18:47

Node.js v18.9.0
error Command failed with exit code 1.
yarn run v1.22.19
$ node --enable-source-maps build/server.js
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn run v1.22.19
$ node --enable-source-maps build/server.js
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by MrBrax** [comment]
weird error, guess i should have echoed out what version it was...

edit **currentversion.dat** in the /data/cache folder and put **0.0.1** in it, i think that should work

**Comment by CappiSteijns** [comment]
> weird error, guess i should have echoed out what version it was...
> 
> edit **currentversion.dat** in the /data/cache folder and put **0.0.1** in it, i think that should work

Thank you, that worked :)
