### ISSUE TITLE
Unable to start container

### ISSUE THREAD

**Issue by soveriegn3** [MrBrax/LiveStreamDVR#303]
Much like issue#300 I'm unable to start my container. I tried following the advice in that issue, and it does not appear to help.

```
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn run v1.22.19
$ node --enable-source-maps build/server.js
/usr/local/share/twitchautomator/server/node_modules/compare-versions/lib/esm/index.js:106
throw new Error(`Invalid argument not valid semver ('${version}' received)`);




Error: Invalid argument not valid semver ('0.6.0
' received)
at validateAndParse (/usr/local/share/twitchautomator/server/node_modules/compare-versions/lib/esm/index.js:106:15)
at compareVersions2 (/usr/local/share/twitchautomator/server/node_modules/compare-versions/lib/esm/index.js:11:16)
at Object.<anonymous> (/usr/local/share/twitchautomator/server/src/index.ts:53:13)
at Module._compile (node:internal/modules/cjs/loader:1119:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
at Module.load (node:internal/modules/cjs/loader:997:32)
at Module._load (node:internal/modules/cjs/loader:838:12)
at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
at node:internal/main/run_main_module:18:47

Node.js v18.9.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn run v1.22.19
$ node --enable-source-maps build/server.js
/usr/local/share/twitchautomator/server/node_modules/compare-versions/lib/esm/index.js:106
throw new Error(`Invalid argument not valid semver ('${version}' received)`);




Error: Invalid argument not valid semver ('0.0.1
' received)
at validateAndParse (/usr/local/share/twitchautomator/server/node_modules/compare-versions/lib/esm/index.js:106:15)
at compareVersions2 (/usr/local/share/twitchautomator/server/node_modules/compare-versions/lib/esm/index.js:11:16)
at Object.<anonymous> (/usr/local/share/twitchautomator/server/src/index.ts:53:13)
at Module._compile (node:internal/modules/cjs/loader:1119:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
at Module.load (node:internal/modules/cjs/loader:997:32)
at Module._load (node:internal/modules/cjs/loader:838:12)
at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
at node:internal/main/run_main_module:18:47

Node.js v18.9.0
error Command failed with exit code 1.
```

**Comment by MrBrax** [comment]
is there a newline in the currentversion file?

**Comment by soveriegn3** [comment]
There was a newline, my bad on missing that. Removing the newline and setting \cache\currentversion.dat to 0.0.1 worked.
