### ISSUE TITLE
Updating (via docker) always breaks LiveStreamDVR

### ISSUE THREAD

**Issue by ermosk** [MrBrax/LiveStreamDVR#325]
Whenever I update LiveStreamDVR Docker, it breaks and have to delete the channels.json and re-configure.

`
Channel with UUID fb0ae2f4-11e8-4884-b9da-6e26f4cef9a9 not found in list: f3005621-76b7-42fd-991f-6f5498f190c8, 0c037004-d4ad-4466-8635-3523b94e2d5c
/usr/local/share/twitchautomator/server/src/Core/Providers/Twitch/TwitchVOD.ts:1503
        if (!channel) throw new Error(`No channel found for getChannel (uuid: ${this.channel_uuid})`);
                            ^

Error: No channel found for getChannel (uuid: fb0ae2f4-11e8-4884-b9da-6e26f4cef9a9)
    at TwitchVOD.getChannel (/usr/local/share/twitchautomator/server/src/Core/Providers/Twitch/TwitchVOD.ts:1503:29)
    at TwitchVOD.setupStreamNumber (/usr/local/share/twitchautomator/server/src/Core/Providers/Twitch/TwitchVOD.ts:1570:30)
    at TwitchVOD.postLoad (/usr/local/share/twitchautomator/server/src/Core/Providers/Twitch/TwitchVOD.ts:1581:14)
    at <anonymous> (/usr/local/share/twitchautomator/server/src/Core/LiveStreamDVR.ts:137:57)
    at Array.forEach (<anonymous>)
    at _LiveStreamDVR.loadChannels (/usr/local/share/twitchautomator/server/src/Core/LiveStreamDVR.ts:137:38)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Function.init (/usr/local/share/twitchautomator/server/src/Core/Config.ts:814:9)

Node.js v18.10.0
error Command failed with exit code 1.
`

This is the error I get, although of course the Channel UUID changes each time

**Comment by ermosk** [comment]
@MrBrax - If you merge it in now, I can give it a go (I haven't deleted my channels.json) and confirm whether fix worked or not.

**Comment by ermosk** [comment]
That fixed it

**Comment by MrBrax** [comment]
does it warn about channels not having uuids? weird
