### ISSUE TITLE
Recording failed due to capture error

### ISSUE THREAD

**Issue by akumar95** [MrBrax/LiveStreamDVR#388]
Hi,

It seems every streamer that I have added has resulted in a capture failure. Here is a log of it happening:

```
2022-12-02 22:40:55.846 | automator.handle <INFO> Automator stream.online event for cackai2 (retry 0)
2022-12-02 22:40:55.850 | automator.handle <INFO> cackai2 stream has ID 40570752873, started 2022-12-02T22:40:44Z
Notifying clients: cackai2 is live!: Just Chatting
Does t, category streamOnline
2022-12-02 22:40:55.857 | automator.download <ERROR> VOD ID already exists for cackai2
2022-12-02 22:40:55.861 | channel <INFO> Create VOD JSON for cackai2: cackai2_2022-12-02T22_40_44Z_40570752873.json @ /usr/local/share/twitchautomator/data/storage/vods/cackai2/cackai2_2022-12-02T22_40_44Z_40570752873
2022-12-02 22:40:55.863 | vod.saveJSON <SUCCESS> Saving JSON of cackai2_2022-12-02T22_40_44Z_40570752873  (create json)
2022-12-02 22:40:55.866 | vod <ERROR> No chapters on cackai2_2022-12-02T22_40_44Z_40570752873!
2022-12-02 22:40:55.867 | vod.load <WARNING> Loaded VOD cackai2_2022-12-02T22_40_44Z_40570752873 is not finalized!
Broadcasting data to 1 clients: {"server":true,"action":"start_download","data":{"vod":{"provide...
2022-12-02 22:40:55.872 | vod.saveJSON <WARNING> Saving JSON of cackai2_2022-12-02T22_40_44Z_40570752873 with no chapters!!
2022-12-02 22:40:55.873 | vod.saveJSON <SUCCESS> Saving JSON of cackai2_2022-12-02T22_40_44Z_40570752873  (is_capturing set)
2022-12-02 22:40:55.875 | automator.download <INFO> Update game for cackai2_2022-12-02T22_40_44Z_40570752873
2022-12-02 22:40:55.875 | automator.updateGame <SUCCESS> Channel data for cackai2 fetched from cache.
2022-12-02 22:40:55.877 | vod.addChapter <INFO> Adding chapter Does t (Just Chatting) to cackai2_2022-12-02T22_40_44Z_40570752873
2022-12-02 22:40:55.878 | chapter <WARNING> No next chapter or vod end time for chapter Does t (2022-11-25T10:10:29.289Z), duration will probably be 0.
2022-12-02 22:40:55.878 | vod.saveJSON <SUCCESS> Saving JSON of cackai2_2022-12-02T22_40_44Z_40570752873  (game update)
Broadcasting data to 1 clients: {"server":true,"action":"chapter_update","data":{"chapter":{"tit...
2022-12-02 22:40:55.881 | automator.updateGame <SUCCESS> Stream updated on 'cackai2' to 'Just Chatting' (Does t) using cache.
Notifying clients: cackai2 is now streaming Just Chatting!: Does t, category streamStatusChange
2022-12-02 22:40:55.886 | vod.saveJSON <SUCCESS> Saving JSON of cackai2_2022-12-02T22_40_44Z_40570752873  (dt_capture_started set)
2022-12-02 22:40:55.887 | automator.captureVideo <INFO> Starting capture with filename cackai2_2022-12-02T22_40_44Z_40570752873.ts
2022-12-02 22:40:55.894 | automator.captureVideo <SUCCESS> Spawned process 69 for capture_cackai2_40570752873
2022-12-02 22:40:55.910 | job <INFO> Save job capture_cackai2_40570752873 with PID 69 to /usr/local/share/twitchautomator/data/cache/pids/capture_cackai2_40570752873.json
Broadcasting data to 1 clients: {"server":true,"action":"job_save","data":{"job_name":"capture_c...
Broadcasting data to 1 clients: {"server":true,"action":"start_capture","data":{"vod":{"provider...
108.162.246.175 - - [02/Dec/2022:22:40:55 +0000] "POST /api/v0/hook/twitch HTTP/1.1" 200 0 "-" "Go-http-client/1.1"
2022-12-02 22:40:55.920 | hook <INFO> Hook called with message ID E9UMvW4-TqlovNN77rstloAIZ5LhbxvQA1ryinSonCQ=, version 1, type stream.online (retry 0, type notification, date 2022-12-02T22:40:55.493290619Z)
2022-12-02 22:40:55.926 | automator.handle <INFO> Automator stream.online event for cackai2 (retry 0)
2022-12-02 22:40:55.927 | automator.handle <INFO> cackai2 is already live, yet another stream online event received.
2022-12-02 22:40:55.929 | automator.handle <INFO> cackai2 stream has ID 40570752873, started 2022-12-02T22:40:44Z
2022-12-02 22:40:55.930 | automator.handle <INFO> Channel cackai2 online, but vod cackai2_2022-12-02T22_40_44Z_40570752873 already exists, skipping
2022-12-02 22:40:55.932 | automator.download <ERROR> Fallback capture failed for cackai2: Fallback capture disabled
Error: Fallback capture disabled
    at TwitchAutomator.fallbackCapture (/usr/local/share/twitchautomator/server/src/Core/Providers/Base/BaseAutomator.ts:1176:35)
    at TwitchAutomator.handle (/usr/local/share/twitchautomator/server/src/Core/Providers/Twitch/TwitchAutomator.ts:153:22)
    at HookTwitch (/usr/local/share/twitchautomator/server/src/Controllers/Hook.ts:200:28)
    at Layer.handle3 (/usr/local/share/twitchautomator/server/.yarn/cache/express-npm-4.18.2-bb15ff679a-3c4b9b0768.zip/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/local/share/twitchautomator/server/.yarn/cache/express-npm-4.18.2-bb15ff679a-3c4b9b0768.zip/node_modules/express/lib/router/route.js:144:13)
    at AuthCore (/usr/local/share/twitchautomator/server/src/Helpers/Auth.ts:82:5)
    at Layer.handle3 (/usr/local/share/twitchautomator/server/.yarn/cache/express-npm-4.18.2-bb15ff679a-3c4b9b0768.zip/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/local/share/twitchautomator/server/.yarn/cache/express-npm-4.18.2-bb15ff679a-3c4b9b0768.zip/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/usr/local/share/twitchautomator/server/.yarn/cache/express-npm-4.18.2-bb15ff679a-3c4b9b0768.zip/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle3 (/usr/local/share/twitchautomator/server/.yarn/cache/express-npm-4.18.2-bb15ff679a-3c4b9b0768.zip/node_modules/express/lib/router/layer.js:95:5)
172.71.150.15 - - [02/Dec/2022:22:40:56 +0000] "POST /api/v0/hook/twitch HTTP/1.1" 200 0 "-" "Go-http-client/1.1"
2022-12-02 22:40:56.606 | automator.captureVideo <WARNING> No streams found for cackai2_2022-12-02T22_40_44Z_40570752873, retrying...
Broadcasting data to 1 clients: {"server":true,"action":"job_update","data":{"job_name":"capture...
Broadcasting data to 1 clients: {"server":true,"action":"vod_updated","data":{"vod":{"provider":...
Broadcasting data to 1 clients: {"server":true,"action":"vod_updated","data":{"vod":{"provider":...
108.162.210.162 - - [02/Dec/2022:22:41:19 +0000] "GET /api/v0/channels HTTP/1.1" 200 121963 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36"
108.162.210.163 - - [02/Dec/2022:22:41:21 +0000] "GET /api/v0/log/2022-12-02/0 HTTP/1.1" 200 311256 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36"
2022-12-02 22:41:47.321 | automator.captureVideo <ERROR> Capturing of cackai2_2022-12-02T22_40_44Z_40570752873 failed, no streams available!
2022-12-02 22:41:47.389 | automator.captureVideo <ERROR> Job capture_cackai2_40570752873 exited with code 1, signal null
2022-12-02 22:41:47.390 | job <INFO> Clear job capture_cackai2_40570752873 with PID 69
Broadcasting data to 1 clients: {"server":true,"action":"job_clear","data":{"job_name":"capture_...
2022-12-02 22:41:47.391 | job <SUCCESS> Job capture_cackai2_40570752873 removed from jobs list
2022-12-02 22:41:47.392 | automator.captureVideo <ERROR> Capture cackai2_2022-12-02T22_40_44Z_40570752873 failed
2022-12-02 22:41:47.392 | automator.download <FATAL> Failed to capture video: false
2022-12-02 22:41:47.393 | vod.saveJSON <SUCCESS> Saving JSON of cackai2_2022-12-02T22_40_44Z_40570752873  (capture fail)
Broadcasting data to 1 clients: {"server":true,"action":"job_clear","data":{"job_name":"capture_...
Broadcasting data to 1 clients: {"server":true,"action":"vod_updated","data":{"vod":{"provider":...
Broadcasting data to 1 clients: {"server":true,"action":"job_clear","data":{"job_name":"capture_...
```

On the latest docker master. Have tried Reset Channels and subscribing to added channels again but the problem persists. Any idea on how to fix this without removing the 5+ channels I have?

**Comment by MrBrax** [comment]
it says no streams available, what's the quality configs for those?

**Comment by akumar95** [comment]
> it says no streams available, what's the quality configs for those?

Hey so sorry I should have debugged a little more opening this issue. Turns out if you log out of twitch and back in it changes your Auth token. I had my old Auth in the .txt file which was causing all the issues. Updated and everything works as expected.

**Comment by MrBrax** [comment]
can you check the streamlink capture log and see if there's anything indicating that your session is broken?
