### ISSUE TITLE
got error while trying to "yarn run build" in client-vue directory 

### ISSUE THREAD

**Issue by 111100001** [MrBrax/LiveStreamDVR#511]
**Describe the bug**
i'm performing a new installation of this repo. i did all the steps with no errors until i ran yarn run build in the client-vue directory and got this error: 

```
ubuntu@archiver:~/DVR/LiveStreamDVR/client-vue$ yarn run build
src/components/vod/VodItemBookmarks.vue:16:38 - error TS2322: Type '{ name: string; params: { uuid: string; }; query: { start: number | undefined; }; } | undefined' is not assignable to type 'RouteLocationRaw'.

16                         <router-link :to="playerLink(bookmark)"> {{ humanDuration(bookmark.offset || 0) }} - {{ bookmark.name }} </router-link>
                                        ~~~

  node_modules/vue-router/dist/vue-router.d.ts:1158:5
    1158     to: RouteLocationRaw;
             ~~
    The expected type comes from property 'to' which is declared here on type 'AllowedComponentProps & ComponentCustomProps & VNodeProps & RouterLinkProps & Record<string, unknown>'


Found 1 error in src/components/vod/VodItemBookmarks.vue:16


ERROR: "type-check" exited with 2.`


```
**To Reproduce**
1. Go to 'client-vue'
2. yarn install
3. yarn run build

**Server:**

Ubuntu

**Comment by MrBrax** [comment]
quite odd, are you using node 22?

**Comment by 111100001** [comment]
yes. i installed all the requirements with their latest versions before
building.

anyways the build is running despite the error and haven't faced any issue
so far.

**Comment by MrBrax** [comment]
the requirements are already packaged with yarn, did it actually install new packages?

**Comment by 111100001** [comment]
sorry by requirements i meant these: 

```

[node.js](https://nodejs.org/) 20+
npm and yarn 3+
Python 3.9+
[pip](https://pypi.org/project/pip/)
[FFmpeg](https://ffmpeg.org/download.html)
[MediaInfo](https://mediaarea.net/en/MediaInfo)
[TwitchDownloader](https://github.com/lay295/TwitchDownloader) 
```
i installed each one separately and made sure they are the latest versions.

However another issue arises: 

i tried to set up the whole thing on my WSL and got a different error when i built client-vue 



lucky@rebyc:~/LiveStreamDVR/client-vue$ yarn run build

```

vite v4.5.0 building for production...
✓ 112 modules transformed.
[vite-plugin-pwa:build] Could not resolve "../../../twitch-vod-chat/dist-lib/twitch-vod-chat" from "src/views/VodPlayerView.vue?vue&type=script&setup=true&lang.ts"
file: /home/lucky/LiveStreamDVR/client-vue/src/views/VodPlayerView.vue?vue&type=script&setup=true&lang.ts
error during build:
RollupError: Could not resolve "../../../twitch-vod-chat/dist-lib/twitch-vod-chat" from "src/views/VodPlayerView.vue?vue&type=script&setup=true&lang.ts"
    at error (file:///home/lucky/LiveStreamDVR/client-vue/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:2287:30)
    at ModuleLoader.handleInvalidResolvedId (file:///home/lucky/LiveStreamDVR/client-vue/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:24860:24)
    at file:///home/lucky/LiveStreamDVR/client-vue/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:24822:26
ERROR: "build-only" exited with 1.
```

**Comment by MrBrax** [comment]
i would advise to use the docker container if you can, but it seems like you haven't built twitch-vod-chat yet

**Comment by 111100001** [comment]
closed because everything is running smoothly so far
